/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionUsuarios.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
gestion_biblioteca_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		datos_credencial abrirsesion_1_arg;
		datos_usuario registrarusuario_1_arg;
		datos_prestamo registrarprestamo_1_arg;
		char *consultarusuario_1_arg;
		char *consultarlibros_1_arg;
		char *consultarprestamo_1_arg;
		datos_prestamo realizardevolucion_1_arg;
		char *consultarmulta_1_arg;
		char *consultarmultasusuario_1_arg;
		char *cancelarmulta_1_arg;
		datos_credencial esdiadevolucion_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case abrirSesion:
		_xdr_argument = (xdrproc_t) xdr_datos_credencial;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) abrirsesion_1_svc;
		break;

	case registrarUsuario:
		_xdr_argument = (xdrproc_t) xdr_datos_usuario;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) registrarusuario_1_svc;
		break;

	case registrarPrestamo:
		_xdr_argument = (xdrproc_t) xdr_datos_prestamo;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) registrarprestamo_1_svc;
		break;

	case consultarUsuario:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_datos_usuario;
		local = (char *(*)(char *, struct svc_req *)) consultarusuario_1_svc;
		break;

	case consultarLibros:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) consultarlibros_1_svc;
		break;

	case consultarPrestamo:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_datos_prestamo;
		local = (char *(*)(char *, struct svc_req *)) consultarprestamo_1_svc;
		break;

	case realizarDevolucion:
		_xdr_argument = (xdrproc_t) xdr_datos_prestamo;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) realizardevolucion_1_svc;
		break;

	case consultarMulta:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_datos_multa;
		local = (char *(*)(char *, struct svc_req *)) consultarmulta_1_svc;
		break;

	case consultarMultasUsuario:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) consultarmultasusuario_1_svc;
		break;

	case imprimirMultas:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) imprimirmultas_1_svc;
		break;

	case cancelarMulta:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) cancelarmulta_1_svc;
		break;

	case esDiaDevolucion:
		_xdr_argument = (xdrproc_t) xdr_datos_credencial;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) esdiadevolucion_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (gestion_biblioteca, gestion_biblioteca_version);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_biblioteca, gestion_biblioteca_version, gestion_biblioteca_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (gestion_biblioteca, gestion_biblioteca_version, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_biblioteca, gestion_biblioteca_version, gestion_biblioteca_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (gestion_biblioteca, gestion_biblioteca_version, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
