/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONUSUARIOS_H_RPCGEN
#define _GESTIONUSUARIOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30
#define MAXDAT 20
#define MAXID 10

struct datos_fecha {
	int dia;
	int mes;
	int anio;
};
typedef struct datos_fecha datos_fecha;

struct datos_usuario {
	char nombreCompleto[MAXNOM];
	char ocupacion[MAXDAT];
	char usuario[MAXDAT];
	char clave[MAXDAT];
};
typedef struct datos_usuario datos_usuario;

struct datos_credencial {
	char usuario[MAXDAT];
	char clave[MAXDAT];
	int diaIngreso;
	int mesIngreso;
	int anioIngreso;
};
typedef struct datos_credencial datos_credencial;

struct datos_prestamo {
	char usuario[MAXDAT];
	char idLibro[MAXID];
	int diaPrestamo;
	int mesPrestamo;
	int anioPrestamo;
	int diaPlazoMax;
	int mesPlazoMax;
	int anioPlazoMax;
	int diaDevolucion;
	int mesDevolucion;
	int anioDevolucion;
};
typedef struct datos_prestamo datos_prestamo;

struct datos_libro {
	char id[MAXID];
	char areaConocimiento[MAXDAT];
	char nombre[MAXNOM];
	char autor[MAXNOM];
	char editorial[MAXDAT];
};
typedef struct datos_libro datos_libro;

struct datos_multa {
	char idMulta[MAXID];
	char usuario[MAXDAT];
	char idLibro[MAXID];
	int diaPrestamo;
	int mesPrestamo;
	int anioPrestamo;
	int diaDevolucion;
	int mesDevolucion;
	int anioDevolucion;
	int diasRetraso;
	int valorMulta;
};
typedef struct datos_multa datos_multa;

#define gestion_biblioteca 0x20000021
#define gestion_biblioteca_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define abrirSesion 1
extern  bool_t * abrirsesion_1(datos_credencial *, CLIENT *);
extern  bool_t * abrirsesion_1_svc(datos_credencial *, struct svc_req *);
#define registrarUsuario 2
extern  bool_t * registrarusuario_1(datos_usuario *, CLIENT *);
extern  bool_t * registrarusuario_1_svc(datos_usuario *, struct svc_req *);
#define registrarPrestamo 3
extern  bool_t * registrarprestamo_1(datos_prestamo *, CLIENT *);
extern  bool_t * registrarprestamo_1_svc(datos_prestamo *, struct svc_req *);
#define consultarUsuario 4
extern  datos_usuario * consultarusuario_1(char **, CLIENT *);
extern  datos_usuario * consultarusuario_1_svc(char **, struct svc_req *);
#define consultarLibros 5
extern  char ** consultarlibros_1(char **, CLIENT *);
extern  char ** consultarlibros_1_svc(char **, struct svc_req *);
#define consultarPrestamo 6
extern  datos_prestamo * consultarprestamo_1(char **, CLIENT *);
extern  datos_prestamo * consultarprestamo_1_svc(char **, struct svc_req *);
#define realizarDevolucion 7
extern  bool_t * realizardevolucion_1(datos_prestamo *, CLIENT *);
extern  bool_t * realizardevolucion_1_svc(datos_prestamo *, struct svc_req *);
#define consultarMulta 8
extern  datos_multa * consultarmulta_1(char **, CLIENT *);
extern  datos_multa * consultarmulta_1_svc(char **, struct svc_req *);
#define consultarMultasUsuario 9
extern  int * consultarmultasusuario_1(char **, CLIENT *);
extern  int * consultarmultasusuario_1_svc(char **, struct svc_req *);
#define imprimirMultas 10
extern  char ** imprimirmultas_1(void *, CLIENT *);
extern  char ** imprimirmultas_1_svc(void *, struct svc_req *);
#define cancelarMulta 11
extern  bool_t * cancelarmulta_1(char **, CLIENT *);
extern  bool_t * cancelarmulta_1_svc(char **, struct svc_req *);
#define esDiaDevolucion 12
extern  char ** esdiadevolucion_1(datos_credencial *, CLIENT *);
extern  char ** esdiadevolucion_1_svc(datos_credencial *, struct svc_req *);
extern int gestion_biblioteca_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define abrirSesion 1
extern  bool_t * abrirsesion_1();
extern  bool_t * abrirsesion_1_svc();
#define registrarUsuario 2
extern  bool_t * registrarusuario_1();
extern  bool_t * registrarusuario_1_svc();
#define registrarPrestamo 3
extern  bool_t * registrarprestamo_1();
extern  bool_t * registrarprestamo_1_svc();
#define consultarUsuario 4
extern  datos_usuario * consultarusuario_1();
extern  datos_usuario * consultarusuario_1_svc();
#define consultarLibros 5
extern  char ** consultarlibros_1();
extern  char ** consultarlibros_1_svc();
#define consultarPrestamo 6
extern  datos_prestamo * consultarprestamo_1();
extern  datos_prestamo * consultarprestamo_1_svc();
#define realizarDevolucion 7
extern  bool_t * realizardevolucion_1();
extern  bool_t * realizardevolucion_1_svc();
#define consultarMulta 8
extern  datos_multa * consultarmulta_1();
extern  datos_multa * consultarmulta_1_svc();
#define consultarMultasUsuario 9
extern  int * consultarmultasusuario_1();
extern  int * consultarmultasusuario_1_svc();
#define imprimirMultas 10
extern  char ** imprimirmultas_1();
extern  char ** imprimirmultas_1_svc();
#define cancelarMulta 11
extern  bool_t * cancelarmulta_1();
extern  bool_t * cancelarmulta_1_svc();
#define esDiaDevolucion 12
extern  char ** esdiadevolucion_1();
extern  char ** esdiadevolucion_1_svc();
extern int gestion_biblioteca_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datos_fecha (XDR *, datos_fecha*);
extern  bool_t xdr_datos_usuario (XDR *, datos_usuario*);
extern  bool_t xdr_datos_credencial (XDR *, datos_credencial*);
extern  bool_t xdr_datos_prestamo (XDR *, datos_prestamo*);
extern  bool_t xdr_datos_libro (XDR *, datos_libro*);
extern  bool_t xdr_datos_multa (XDR *, datos_multa*);

#else /* K&R C */
extern bool_t xdr_datos_fecha ();
extern bool_t xdr_datos_usuario ();
extern bool_t xdr_datos_credencial ();
extern bool_t xdr_datos_prestamo ();
extern bool_t xdr_datos_libro ();
extern bool_t xdr_datos_multa ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONUSUARIOS_H_RPCGEN */
