/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionUsuarios.h"

bool_t
xdr_datos_fecha (XDR *xdrs, datos_fecha *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dia))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anio))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_usuario (XDR *xdrs, datos_usuario *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombreCompleto, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ocupacion, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->usuario, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->clave, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_credencial (XDR *xdrs, datos_credencial *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->usuario, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->clave, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->diaIngreso))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mesIngreso))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anioIngreso))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_prestamo (XDR *xdrs, datos_prestamo *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->usuario, MAXDAT,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->idLibro, MAXID,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 9 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->diaPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mesPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anioPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->diaPlazoMax))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mesPlazoMax))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anioPlazoMax))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->diaDevolucion))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mesDevolucion))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anioDevolucion))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->diaPrestamo);
			IXDR_PUT_LONG(buf, objp->mesPrestamo);
			IXDR_PUT_LONG(buf, objp->anioPrestamo);
			IXDR_PUT_LONG(buf, objp->diaPlazoMax);
			IXDR_PUT_LONG(buf, objp->mesPlazoMax);
			IXDR_PUT_LONG(buf, objp->anioPlazoMax);
			IXDR_PUT_LONG(buf, objp->diaDevolucion);
			IXDR_PUT_LONG(buf, objp->mesDevolucion);
			IXDR_PUT_LONG(buf, objp->anioDevolucion);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->usuario, MAXDAT,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->idLibro, MAXID,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 9 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->diaPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mesPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anioPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->diaPlazoMax))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mesPlazoMax))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anioPlazoMax))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->diaDevolucion))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mesDevolucion))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anioDevolucion))
				 return FALSE;
		} else {
			objp->diaPrestamo = IXDR_GET_LONG(buf);
			objp->mesPrestamo = IXDR_GET_LONG(buf);
			objp->anioPrestamo = IXDR_GET_LONG(buf);
			objp->diaPlazoMax = IXDR_GET_LONG(buf);
			objp->mesPlazoMax = IXDR_GET_LONG(buf);
			objp->anioPlazoMax = IXDR_GET_LONG(buf);
			objp->diaDevolucion = IXDR_GET_LONG(buf);
			objp->mesDevolucion = IXDR_GET_LONG(buf);
			objp->anioDevolucion = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->usuario, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->idLibro, MAXID,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->diaPrestamo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mesPrestamo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anioPrestamo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->diaPlazoMax))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mesPlazoMax))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anioPlazoMax))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->diaDevolucion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mesDevolucion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anioDevolucion))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_libro (XDR *xdrs, datos_libro *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->id, MAXID,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->areaConocimiento, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->autor, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->editorial, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_multa (XDR *xdrs, datos_multa *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->idMulta, MAXID,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->usuario, MAXDAT,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->idLibro, MAXID,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 8 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->diaPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mesPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anioPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->diaDevolucion))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mesDevolucion))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anioDevolucion))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->diasRetraso))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->valorMulta))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->diaPrestamo);
			IXDR_PUT_LONG(buf, objp->mesPrestamo);
			IXDR_PUT_LONG(buf, objp->anioPrestamo);
			IXDR_PUT_LONG(buf, objp->diaDevolucion);
			IXDR_PUT_LONG(buf, objp->mesDevolucion);
			IXDR_PUT_LONG(buf, objp->anioDevolucion);
			IXDR_PUT_LONG(buf, objp->diasRetraso);
			IXDR_PUT_LONG(buf, objp->valorMulta);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->idMulta, MAXID,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->usuario, MAXDAT,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->idLibro, MAXID,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 8 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->diaPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mesPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anioPrestamo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->diaDevolucion))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mesDevolucion))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anioDevolucion))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->diasRetraso))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->valorMulta))
				 return FALSE;
		} else {
			objp->diaPrestamo = IXDR_GET_LONG(buf);
			objp->mesPrestamo = IXDR_GET_LONG(buf);
			objp->anioPrestamo = IXDR_GET_LONG(buf);
			objp->diaDevolucion = IXDR_GET_LONG(buf);
			objp->mesDevolucion = IXDR_GET_LONG(buf);
			objp->anioDevolucion = IXDR_GET_LONG(buf);
			objp->diasRetraso = IXDR_GET_LONG(buf);
			objp->valorMulta = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->idMulta, MAXID,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->usuario, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->idLibro, MAXID,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->diaPrestamo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mesPrestamo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anioPrestamo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->diaDevolucion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mesDevolucion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anioDevolucion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->diasRetraso))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valorMulta))
		 return FALSE;
	return TRUE;
}
